### ISSUE TITLE
white window and stack trace

### ISSUE THREAD

**Issue by davidak** [pathephone/pathephone-desktop#226]
I have it running for about 3 days, now it crashed. I see a white window and this log:

```
[davidak@X230:~]$ appimage-run Downloads/pathephone-desktop-2.2.1-x86_64.AppImage 
-- starting ipc
-- loading main window
Gtk-Message: 05:54:49.411: GtkDialog mapped without a transient parent. This is discouraged.

  ipfs api running on /ip4/127.0.0.1/tcp/43021
  ipfs gateway running on /ip4/127.0.0.1/tcp/39001
  
Gtk-Message: 06:16:58.365: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: 07:00:10.389: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: 07:01:26.417: GtkDialog mapped without a transient parent. This is discouraged.
(node:2794) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 message listeners added. Use emitter.setMaxListeners() to increase limit
Gtk-Message: 07:04:27.298: GtkDialog mapped without a transient parent. This is discouraged.
(node:2794) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 message listeners added. Use emitter.setMaxListeners() to increase limit
(node:2794) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 message listeners added. Use emitter.setMaxListeners() to increase limit
Error: No parser found for extension: .m3u
    at /home/davidak/.cache/appimage-run/f9094b2d52c27b62387138c32578e864d4a23ab898cbde8581fff0484669ccf7/squashfs-root/resources/app.asar/node_modules/music-metadata/lib/ParserFactory.js:41:23
    at tryCatch (/home/davidak/.cache/appimage-run/f9094b2d52c27b62387138c32578e864d4a23ab898cbde8581fff0484669ccf7/squashfs-root/resources/app.asar/node_modules/es6-promise/dist/es6-promise.js:409:12)
    at invokeCallback (/home/davidak/.cache/appimage-run/f9094b2d52c27b62387138c32578e864d4a23ab898cbde8581fff0484669ccf7/squashfs-root/resources/app.asar/node_modules/es6-promise/dist/es6-promise.js:424:13)
    at publish (/home/davidak/.cache/appimage-run/f9094b2d52c27b62387138c32578e864d4a23ab898cbde8581fff0484669ccf7/squashfs-root/resources/app.asar/node_modules/es6-promise/dist/es6-promise.js:398:7)
    at flush (/home/davidak/.cache/appimage-run/f9094b2d52c27b62387138c32578e864d4a23ab898cbde8581fff0484669ccf7/squashfs-root/resources/app.asar/node_modules/es6-promise/dist/es6-promise.js:128:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Gtk-Message: 07:14:16.014: GtkDialog mapped without a transient parent. This is discouraged.
(node:2794) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 message listeners added. Use emitter.setMaxListeners() to increase limit
Error: No parser found for extension: .m3u
    at /home/davidak/.cache/appimage-run/f9094b2d52c27b62387138c32578e864d4a23ab898cbde8581fff0484669ccf7/squashfs-root/resources/app.asar/node_modules/music-metadata/lib/ParserFactory.js:41:23
    at tryCatch (/home/davidak/.cache/appimage-run/f9094b2d52c27b62387138c32578e864d4a23ab898cbde8581fff0484669ccf7/squashfs-root/resources/app.asar/node_modules/es6-promise/dist/es6-promise.js:409:12)
    at invokeCallback (/home/davidak/.cache/appimage-run/f9094b2d52c27b62387138c32578e864d4a23ab898cbde8581fff0484669ccf7/squashfs-root/resources/app.asar/node_modules/es6-promise/dist/es6-promise.js:424:13)
    at publish (/home/davidak/.cache/appimage-run/f9094b2d52c27b62387138c32578e864d4a23ab898cbde8581fff0484669ccf7/squashfs-root/resources/app.asar/node_modules/es6-promise/dist/es6-promise.js:398:7)
    at flush (/home/davidak/.cache/appimage-run/f9094b2d52c27b62387138c32578e864d4a23ab898cbde8581fff0484669ccf7/squashfs-root/resources/app.asar/node_modules/es6-promise/dist/es6-promise.js:128:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Error: No parser found for extension: .m3u
    at /home/davidak/.cache/appimage-run/f9094b2d52c27b62387138c32578e864d4a23ab898cbde8581fff0484669ccf7/squashfs-root/resources/app.asar/node_modules/music-metadata/lib/ParserFactory.js:41:23
    at tryCatch (/home/davidak/.cache/appimage-run/f9094b2d52c27b62387138c32578e864d4a23ab898cbde8581fff0484669ccf7/squashfs-root/resources/app.asar/node_modules/es6-promise/dist/es6-promise.js:409:12)
    at invokeCallback (/home/davidak/.cache/appimage-run/f9094b2d52c27b62387138c32578e864d4a23ab898cbde8581fff0484669ccf7/squashfs-root/resources/app.asar/node_modules/es6-promise/dist/es6-promise.js:424:13)
    at publish (/home/davidak/.cache/appimage-run/f9094b2d52c27b62387138c32578e864d4a23ab898cbde8581fff0484669ccf7/squashfs-root/resources/app.asar/node_modules/es6-promise/dist/es6-promise.js:398:7)
    at flush (/home/davidak/.cache/appimage-run/f9094b2d52c27b62387138c32578e864d4a23ab898cbde8581fff0484669ccf7/squashfs-root/resources/app.asar/node_modules/es6-promise/dist/es6-promise.js:128:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Gtk-Message: 07:42:47.755: GtkDialog mapped without a transient parent. This is discouraged.
(node:2794) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 message listeners added. Use emitter.setMaxListeners() to increase limit
Gtk-Message: 07:45:39.072: GtkDialog mapped without a transient parent. This is discouraged.
Error: No parser found for extension: .m3u
    at /home/davidak/.cache/appimage-run/f9094b2d52c27b62387138c32578e864d4a23ab898cbde8581fff0484669ccf7/squashfs-root/resources/app.asar/node_modules/music-metadata/lib/ParserFactory.js:41:23
    at tryCatch (/home/davidak/.cache/appimage-run/f9094b2d52c27b62387138c32578e864d4a23ab898cbde8581fff0484669ccf7/squashfs-root/resources/app.asar/node_modules/es6-promise/dist/es6-promise.js:409:12)
    at invokeCallback (/home/davidak/.cache/appimage-run/f9094b2d52c27b62387138c32578e864d4a23ab898cbde8581fff0484669ccf7/squashfs-root/resources/app.asar/node_modules/es6-promise/dist/es6-promise.js:424:13)
    at publish (/home/davidak/.cache/appimage-run/f9094b2d52c27b62387138c32578e864d4a23ab898cbde8581fff0484669ccf7/squashfs-root/resources/app.asar/node_modules/es6-promise/dist/es6-promise.js:398:7)
    at flush (/home/davidak/.cache/appimage-run/f9094b2d52c27b62387138c32578e864d4a23ab898cbde8581fff0484669ccf7/squashfs-root/resources/app.asar/node_modules/es6-promise/dist/es6-promise.js:128:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Gtk-Message: 07:47:41.240: GtkDialog mapped without a transient parent. This is discouraged.
(node:2794) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 message listeners added. Use emitter.setMaxListeners() to increase limit
(node:2794) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 message listeners added. Use emitter.setMaxListeners() to increase limit
Gtk-Message: 07:51:16.531: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: 07:51:26.969: GtkDialog mapped without a transient parent. This is discouraged.
(node:2794) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 message listeners added. Use emitter.setMaxListeners() to increase limit
(node:2794) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 message listeners added. Use emitter.setMaxListeners() to increase limit
(node:2794) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 message listeners added. Use emitter.setMaxListeners() to increase limit
(node:2794) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 message listeners added. Use emitter.setMaxListeners() to increase limit
Gtk-Message: 07:57:12.049: GtkDialog mapped without a transient parent. This is discouraged.
(node:2794) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 message listeners added. Use emitter.setMaxListeners() to increase limit
(node:2794) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 message listeners added. Use emitter.setMaxListeners() to increase limit

<--- Last few GCs --->

[3471:0x1f3558ce2000] 359175462 ms: Mark-sweep 2047.7 (2390.5) -> 2047.7 (2390.5) MB, 3148.0 / 0.1 ms  allocation failure GC in old space requested
[3471:0x1f3558ce2000] 359178609 ms: Mark-sweep 2047.7 (2390.5) -> 2047.7 (2390.5) MB, 3139.2 / 30.8 ms  last resort GC in old space requested
[3471:0x1f3558ce2000] 359181715 ms: Mark-sweep 2047.7 (2390.5) -> 2047.7 (2390.5) MB, 3105.8 / 26.7 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x28a2df774ae9 <String[7]: file://>
    2: n [file:///home/davidak/.cache/appimage-run/f9094b2d52c27b62387138c32578e864d4a23ab898cbde8581fff0484669ccf7/squashfs-root/resources/app.asar/renderer.js:1] [bytecode=0x59d84fa999 offset=26](this=0x2e4fe3703b11 <Worker map = 0x3b02ca37fc9>,/* anonymous */=0x27e77977e991 <MessageEvent map = 0x3b02ca3bd51>)

==== Details ================================================

[2]: n [fi...

```

after i quit the window, i got the rest of the output: https://gist.github.com/davidak/01228ceb9420042c89fee54329414618

I'm on NixOS, so i have to use [appimage-run](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/package-management/appimage-run/default.nix) which creates an environment where AppImages can run.

pathephone 2.2.1-x86_64.AppImage
NixOS 18.03.133245.d16a7abceb7 (Impala)

**Comment by negamaxi** [comment]
@davidak errors of this kind are expected: 
```bash
{ Error: failed to get block for QmaJiNGbVcATviwXZZVuT6qwcFs5SrvHeGkPEufQF3ZZa8: promise channel was closed
```
They indicate that some of requested p2p data (album covers most of the time) haven't been downloaded when you closed the application.

As for .m3u parsing errors - did they happen when you have tried to upload some files?

**Comment by davidak** [comment]
>As for .m3u parsing errors - did they happen when you have tried to upload some files?

yes. i have thrown the whole folder in
